name: Airflow CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
    DOCKER_USERNAME: achevsky
    GIT_USERNAME: kulichevskiy
    IMAGE_NAME: airflow
    EMAIL: alexey.kulichevskiy@gmail.com
    NAME: Alexey Kulichevskiy

jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
      
#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.10'
          
#     #   - name: Install dependencies
#     #     run: |
#     #       pip install -r requirements.txt
          
#       - name: Lint with Flake8
#         run: |
#           pip install flake8
#           flake8 .
          
#       - name: Run tests
#         run: |
#           # Add your commands to run tests here
#           echo "Running tests..."

  deploy:
    # needs: test
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4       

        - name: Deploy Code to Server
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22 # or your custom port
            source: "." # or specify directories/files to copy
            target: "airflow"        

        # - name: Pull the container and restart docker-compose
        #   uses: appleboy/ssh-action@master
        #   env:
        #     IMAGE_TAG: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        #   with:
        #     host: ${{ secrets.EC2_HOST }}
        #     username: ubuntu
        #     port: 22
        #     key: ${{ secrets.SSH_PRIVATE_KEY }}
        #     script: |
        #         export AIRFLOW_IMAGE_NAME=${{ env.IMAGE_TAG }}
        #         export AIRFLOW_UID=$(id -u)
        #         echo -e "AIRFLOW_UID=$(id -u)" > .env
        #         cd airflow

        #         echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin
        #         docker pull ${{ env.IMAGE_TAG }}
        #         docker-compose down
        #         docker-compose up -d