name: Airflow CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    DOCKER_USERNAME: achevsky
    IMAGE_NAME: airflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
    #   - name: Install dependencies
    #     run: |
    #       pip install -r requirements.txt
          
      - name: Lint with Flake8
        run: |
          pip install flake8
          flake8 .
          
      - name: Run tests
        run: |
          # Add your commands to run tests here
          echo "Running tests..."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    env:
        image_tag: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Print Tag
          env:
            image_tag: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          run: |
            echo "Image Tag: ${{ env.image_tag }}"
       
        # - name: Build and push Docker image
        #   run: |
        #     docker build -t ${{ env.image_tag }} .
        #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        #     docker push ${{ env.image_tag }}